[profile.default]
auto_detect_solc = true
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]
fs_permissions = [{ access = "read", path = "./broadcast" }, {access = "read", path = "./img/"}]

[rpc_endpoints]
# allfeat-testnet = "${ALLFEAT_RPC_URL}"
# allfeat-local = "http://127.0.0.1:9944/"
allfeat = "${ALLFEAT_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
